// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FocusController from "./focus_controller.js"
application.register("focus", FocusController)

import HiddenController from "./hidden_controller.js"
application.register("hidden", HiddenController)

import ResizeController from "./resize_controller.js"
application.register("resize", ResizeController)
