// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonSubmitController from "./button_submit_controller.js"
application.register("button-submit", ButtonSubmitController)

import FocusController from "./focus_controller.js"
application.register("focus", FocusController)

import HiddenController from "./hidden_controller.js"
application.register("hidden", HiddenController)

import PopupController from "./popup_controller.js"
application.register("popup", PopupController)

import RemovalsController from "./removals_controller.js"
application.register("removals", RemovalsController)

import ResizeController from "./resize_controller.js"
application.register("resize", ResizeController)
